  monster_id: 100046
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 7873
        }
      }
    }
    groups {
      group_type: STANDARD
    }
  }
