  monster_id: 100205
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 9120
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 9121
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 9224
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 3
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 9122
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 3
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 9123
            }
          }
        }
      }
    }
  }
