  monster_id: 100304
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 5101
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_attributes_available: true
          }
          enemy_skill_id: 5122
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 100
        repeats_every: 2
      }
      children {
        behavior {
          enemy_skill_id: 5106
        }
      }
    }
  }
