  monster_id: 101083
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        if_attributes_available: true
      }
      children {
        behavior {
          enemy_skill_id: 13632
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_attributes_available: true
          }
          enemy_skill_id: 5285
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 5289
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_attributes_available: true
          }
          enemy_skill_id: 5290
        }
      }
    }
  }
