  monster_id: 101167
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 11546
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 2
              }
              children {
                behavior {
                  enemy_skill_id: 902
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 2
              }
              children {
                behavior {
                  enemy_skill_id: 941
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 943
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 944
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 942
                }
              }
            }
          }
        }
      }
    }
  }
