  monster_id: 101458
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 8007
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 3794
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 540
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 600
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 3778
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3767
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 3794
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 540
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 600
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 3778
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3764
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3767
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 3794
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 540
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 600
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 3778
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3766
            }
          }
        }
      }
    }
  }
