  monster_id: 101752
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 1740
        }
      }
    }
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 10929
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 30
              }
              enemy_skill_id: 1731
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 10930
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 1731
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 75
                    use_chance: 100
                  }
                  enemy_skill_id: 1732
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 1731
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 10930
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1730
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              condition {
                hp_threshold: 30
                use_chance: 50
              }
              enemy_skill_id: 1733
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 30
                use_chance: 100
              }
              enemy_skill_id: 1734
            }
          }
        }
      }
    }
  }
