  monster_id: 102383
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3263
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3267
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3268
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 10
              }
              enemy_skill_id: 3270
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 45
                if_attributes_available: true
              }
              enemy_skill_id: 3271
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 45
              }
              enemy_skill_id: 3266
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 55
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3265
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 3264
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3269
            }
          }
        }
      }
    }
  }
