  monster_id: 102551
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 2637
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 2629
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2632
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 33
                      }
                      enemy_skill_id: 2630
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 34
                      }
                      enemy_skill_id: 2631
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 33
                      }
                      enemy_skill_id: 2633
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 2634
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2635
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2636
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 1
                        use_chance: 100
                      }
                      enemy_skill_id: 2642
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
