  monster_id: 102739
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 4798
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8217
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 4802
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 4805
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 4806
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                if_attributes_available: true
              }
              children {
                behavior {
                  enemy_skill_id: 4807
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 4808
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 4809
            }
          }
        }
      }
    }
  }
