  monster_id: 102718
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 8804
        }
      }
    }
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 8755
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                if_attributes_available: true
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 2972
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 2973
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                if_attributes_available: true
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 2974
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 2975
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 2976
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 2990
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 2991
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 2992
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 2993
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 2994
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 2979
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 2978
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 2980
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 2981
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            behavior {
              condition {
                hp_threshold: 30
                use_chance: 50
              }
              enemy_skill_id: 2982
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 30
                use_chance: 100
              }
              enemy_skill_id: 2983
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 2984
            }
          }
        }
      }
    }
  }
