  monster_id: 102788
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 7748
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        use_chance: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 3921
        }
      }
    }
  }
  levels {
    level: 3
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 7748
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7746
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        use_chance: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 3921
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3917
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 3918
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3919
            }
          }
        }
      }
    }
  }
