  monster_id: 103183
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 12862
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 33
                      }
                      enemy_skill_id: 12865
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 33
                      }
                      enemy_skill_id: 12866
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 34
                      }
                      enemy_skill_id: 12867
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 12868
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        trigger_enemies_remaining: 1
                      }
                      enemy_skill_id: 12871
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 12872
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
