  monster_id: 103221
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 5669
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5644
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5647
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 5660
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 5653
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 5654
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 5655
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 5662
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 5661
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            use_chance: 100
            trigger_enemies_remaining: 1
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 5672
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 5656
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 5673
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 5657
                }
              }
            }
          }
        }
      }
    }
  }
  levels {
    level: 6
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 5669
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5644
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 12161
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 5660
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 5653
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 5654
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 5655
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 5662
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 5661
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            use_chance: 100
            trigger_enemies_remaining: 1
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 5672
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 5656
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 5673
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 5657
                }
              }
            }
          }
        }
      }
    }
  }
