  monster_id: 103529
  levels {
    level: 1
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            if_defeated: true
          }
          enemy_skill_id: 6388
        }
      }
    }
  }
