  monster_id: 103575
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 6786
        }
      }
      children {
        behavior {
          enemy_skill_id: 12175
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6766
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 40
              }
              enemy_skill_id: 6780
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 6781
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 40
              }
              enemy_skill_id: 6782
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 34
              }
              enemy_skill_id: 6771
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 33
              }
              enemy_skill_id: 6772
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 33
              }
              enemy_skill_id: 6773
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 6775
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 6778
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 6785
            }
          }
        }
      }
    }
  }
