  monster_id: 103623
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6700
        }
      }
      children {
        behavior {
          enemy_skill_id: 6702
        }
      }
      children {
        behavior {
          enemy_skill_id: 6692
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            use_chance: 100
            global_one_time: true
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 6693
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 6
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 6694
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 6
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 6695
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 6
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 6696
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 6
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 6697
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 6
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 6698
            }
          }
        }
      }
    }
  }
