  monster_id: 103724
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 8210
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7649
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7653
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7652
        }
      }
      children {
        behavior {
          condition {
            trigger_enemies_remaining: 1
          }
          enemy_skill_id: 7655
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7656
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7658
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7657
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7659
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7660
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 7661
        }
      }
    }
  }
