  monster_id: 104616
  levels {
    level: 1
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            if_defeated: true
          }
          enemy_skill_id: 10269
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 10265
        }
      }
    }
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            if_defeated: true
          }
          enemy_skill_id: 10269
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 50
                      }
                      enemy_skill_id: 10263
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10265
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 50
                      }
                      enemy_skill_id: 10263
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10265
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 50
                      }
                      enemy_skill_id: 10263
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10265
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 50
                      }
                      enemy_skill_id: 10263
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10265
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 10
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 50
                      }
                      enemy_skill_id: 10263
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10265
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 12
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 50
                      }
                      enemy_skill_id: 10263
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10265
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 13
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 14
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 50
                      }
                      enemy_skill_id: 10263
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10265
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10262
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10264
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 10266
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10270
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10267
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
