  monster_id: 104757
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11026
        }
      }
      children {
        behavior {
          enemy_skill_id: 11025
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 11027
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 11028
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 11029
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 11030
            }
          }
        }
      }
    }
  }
