  monster_id: 104801
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10758
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 50
              }
              enemy_skill_id: 10760
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 10759
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 10763
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 10
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 10764
            }
          }
        }
      }
    }
  }
