  monster_id: 105005
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 12241
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 33
              }
              enemy_skill_id: 12220
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 33
              }
              enemy_skill_id: 12221
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 34
              }
              enemy_skill_id: 12222
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 12244
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 12245
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 12224
                }
              }
            }
          }
        }
      }
    }
  }
