  monster_id: 1080
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 907
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 964
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 909
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 964
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 910
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 964
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 911
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 964
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 912
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 964
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 10
          }
          children {
            behavior {
              enemy_skill_id: 913
            }
          }
        }
      }
    }
  }
