  monster_id: 1115
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2364
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 2365
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 50
              }
              children {
                behavior {
                  enemy_skill_id: 2367
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 2366
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            use_chance: 100
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 2368
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 2318
            }
          }
        }
      }
    }
  }
