  monster_id: 1361
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 1153
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1154
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 50
                repeats_every: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1155
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 1156
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 1157
                }
              }
            }
          }
        }
      }
    }
  }
