  monster_id: 1363
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1286
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 1287
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 1288
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1289
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 1290
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 1291
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 25
              }
              children {
                behavior {
                  enemy_skill_id: 1306
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 1292
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 1293
                }
              }
            }
          }
        }
      }
    }
  }
