  monster_id: 1507
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 2444
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 30
              }
              enemy_skill_id: 2447
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 30
              }
              enemy_skill_id: 2448
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 30
              }
              enemy_skill_id: 1
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 70
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2445
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 2446
            }
          }
        }
      }
    }
  }
