  monster_id: 1604
  levels {
    level: 5
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 1498
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            group {
              condition {
                hp_threshold: 80
                use_chance: 100
                repeats_every: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1499
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1498
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1500
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 50
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 80
                    use_chance: 100
                  }
                  enemy_skill_id: 1499
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 50
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 1498
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 50
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 80
                    use_chance: 100
                  }
                  enemy_skill_id: 1499
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 50
                    use_chance: 75
                  }
                  enemy_skill_id: 1501
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 1498
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 30
                use_chance: 100
                repeats_every: 3
              }
              children {
                behavior {
                  enemy_skill_id: 1502
                }
              }
            }
          }
        }
      }
    }
  }
