  monster_id: 1660
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 9758
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 9759
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 9769
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 9763
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 9764
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 9767
            }
          }
          children {
            behavior {
              condition {
                use_chance: 25
              }
              enemy_skill_id: 9768
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 9760
            }
          }
        }
      }
    }
  }
