  monster_id: 1732
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3524
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 50
          }
          children {
            behavior {
              enemy_skill_id: 3526
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            use_chance: 100
            global_one_time: true
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3525
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3527
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                global_one_time: true
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3525
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3528
            }
          }
        }
      }
    }
  }
