  monster_id: 1855
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1858
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 5296
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 1858
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 5296
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1859
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 1860
            }
          }
        }
      }
    }
  }
