  monster_id: 193
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 40
      }
      children {
        behavior {
          enemy_skill_id: 131
        }
      }
    }
  }
