  monster_id: 201075
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
        if_attributes_available: true
      }
      children {
        behavior {
          enemy_skill_id: 4263
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 4260
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_attributes_available: true
          }
          enemy_skill_id: 4259
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 4261
        }
      }
    }
  }
