  monster_id: 201762
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 1773
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PASSIVE
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 1773
        }
      }
    }
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 1765
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 40
              }
              enemy_skill_id: 1766
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 70
              }
              enemy_skill_id: 1767
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 75
            use_chance: 100
            trigger_enemies_remaining: 3
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 1768
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 50
                use_chance: 100
                repeats_every: 2
              }
              children {
                behavior {
                  enemy_skill_id: 1769
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 40
                  }
                  enemy_skill_id: 1766
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 70
                  }
                  enemy_skill_id: 1767
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                hp_threshold: 50
                use_chance: 100
                repeats_every: 2
              }
              children {
                behavior {
                  enemy_skill_id: 1769
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 30
                use_chance: 100
                repeats_every: 2
              }
              children {
                behavior {
                  enemy_skill_id: 1770
                }
              }
            }
          }
        }
      }
    }
  }
