  monster_id: 2018
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 2034
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 50
              }
              enemy_skill_id: 2035
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 2036
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 70
            use_chance: 100
            trigger_enemies_remaining: 1
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2037
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 30
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 2038
            }
          }
        }
      }
    }
  }
