  monster_id: 201843
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11283
        }
      }
      children {
        behavior {
          enemy_skill_id: 11281
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 11284
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3544
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3545
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3545
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3544
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 89
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3549
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3544
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 3545
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 3547
            }
          }
          children {
            behavior {
              condition {
                use_chance: 100
              }
              enemy_skill_id: 3546
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                use_chance: 100
              }
              enemy_skill_id: 3550
            }
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 3547
            }
          }
          children {
            behavior {
              condition {
                use_chance: 100
              }
              enemy_skill_id: 3546
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3550
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 3548
                }
              }
            }
          }
        }
      }
    }
  }
