  monster_id: 204415
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 14445
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14446
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 14451
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 14469
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 14452
            }
          }
        }
      }
    }
  }
