  monster_id: 2052
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 2154
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 40
              }
              enemy_skill_id: 2101
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 30
              }
              enemy_skill_id: 2103
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 10
              }
              enemy_skill_id: 2102
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 1
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 90
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2155
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
          }
          children {
            group {
              condition {
                hp_threshold: 90
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 2155
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 70
                    use_chance: 30
                  }
                  enemy_skill_id: 2157
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 40
                  }
                  enemy_skill_id: 2101
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 2103
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 10
                  }
                  enemy_skill_id: 2102
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 1
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 50
                use_chance: 100
                trigger_enemies_remaining: 1
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 2131
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 70
                    use_chance: 30
                  }
                  enemy_skill_id: 2157
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 90
                    use_chance: 100
                  }
                  enemy_skill_id: 2155
                }
              }
            }
          }
        }
      }
    }
  }
