  monster_id: 2055
  levels {
    level: 1
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_defeated: true
          }
          enemy_skill_id: 2892
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 2184
        }
      }
    }
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_defeated: true
          }
          enemy_skill_id: 2892
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2185
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2111
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2186
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2109
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 50
                        use_chance: 100
                      }
                      enemy_skill_id: 2188
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2185
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 2111
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 50
                        use_chance: 100
                      }
                      enemy_skill_id: 2110
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
