  monster_id: 217
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 50
        use_chance: 75
      }
      children {
        behavior {
          enemy_skill_id: 85
        }
      }
    }
  }
