  monster_id: 2184
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 2533
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 2538
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 1
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 2542
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 2537
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 50
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 2543
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 50
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 2540
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 30
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 2541
            }
          }
        }
      }
    }
  }
