  monster_id: 2187
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 5159
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 5160
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 5161
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 3
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
                if_attributes_available: true
              }
              enemy_skill_id: 5162
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
                if_attributes_available: true
              }
              enemy_skill_id: 5163
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 5164
            }
          }
        }
      }
    }
  }
