  monster_id: 2235
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 3989
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3988
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3994
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3993
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3990
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3995
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3996
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3997
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 4000
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                    global_one_time: true
                  }
                  enemy_skill_id: 4001
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3994
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3993
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3990
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3995
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3996
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3997
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 4000
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3994
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3993
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3990
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 4003
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                    global_one_time: true
                  }
                  enemy_skill_id: 4001
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 20
                  }
                  enemy_skill_id: 3994
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3993
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3990
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 4005
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 4006
                }
              }
            }
          }
        }
      }
    }
  }
