  monster_id: 2263
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3088
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                    global_one_time: true
                    trigger_monsters: 1947
                  }
                  enemy_skill_id: 3092
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                    trigger_monsters: 1257
                  }
                  enemy_skill_id: 3090
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 3093
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 3094
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                    global_one_time: true
                    trigger_monsters: 1947
                  }
                  enemy_skill_id: 3092
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                    trigger_monsters: 1257
                  }
                  enemy_skill_id: 3090
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3095
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 3093
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 60
                  }
                  enemy_skill_id: 3094
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 3095
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 2
                trigger_turn_end: 3
              }
              children {
                behavior {
                  enemy_skill_id: 3096
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 3096
                }
              }
            }
          }
        }
      }
    }
  }
