  monster_id: 2418
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 9698
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 9698
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 9687
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 9
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 9688
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 9689
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 9690
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 10
              }
              children {
                behavior {
                  enemy_skill_id: 9697
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 9688
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 9689
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 9690
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 9693
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 2
                trigger_turn_end: 9
              }
              children {
                behavior {
                  enemy_skill_id: 9694
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 9694
                }
              }
            }
          }
        }
      }
    }
  }
