  monster_id: 2555
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 10957
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 10965
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                    if_attributes_available: true
                  }
                  enemy_skill_id: 10966
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 10967
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 10960
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 10962
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 10961
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 10965
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                    if_attributes_available: true
                  }
                  enemy_skill_id: 10966
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 10967
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 10962
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 10961
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 10965
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                    if_attributes_available: true
                  }
                  enemy_skill_id: 10966
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 10967
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 10969
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 10965
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                    if_attributes_available: true
                  }
                  enemy_skill_id: 10966
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 10967
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 10963
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 10970
            }
          }
        }
      }
    }
  }
