  monster_id: 2647
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 2871
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 2875
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 50
              }
              enemy_skill_id: 2874
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 30
              }
              enemy_skill_id: 2873
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 2872
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 10
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 2876
            }
          }
        }
      }
    }
  }
