  monster_id: 2653
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      condition {
        if_attributes_available: true
      }
      children {
        behavior {
          enemy_skill_id: 2720
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 30
      }
      children {
        behavior {
          enemy_skill_id: 2721
        }
      }
    }
  }
