  monster_id: 2658
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 15672
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15689
        }
      }
      children {
        behavior {
          enemy_skill_id: 15690
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 15689
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 15690
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 15691
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 15689
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 15690
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            behavior {
              enemy_skill_id: 15695
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          children {
            behavior {
              enemy_skill_id: 15696
            }
          }
        }
      }
    }
  }
