  monster_id: 2747
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7845
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 10
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 7848
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7855
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7856
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7857
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7858
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7859
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 11
              }
              children {
                behavior {
                  enemy_skill_id: 7863
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 7848
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7855
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7856
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7857
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7858
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7859
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                hp_threshold: 50
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7862
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 11
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 30
                  }
                  enemy_skill_id: 7848
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7855
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7856
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7857
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7858
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 14
                  }
                  enemy_skill_id: 7859
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 12
              }
              children {
                behavior {
                  enemy_skill_id: 7863
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 10
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 7864
            }
          }
        }
      }
    }
  }
