  monster_id: 2787
  levels {
    level: 1
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_defeated: true
          }
          enemy_skill_id: 3910
        }
      }
    }
    groups {
      group_type: STANDARD
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 3906
        }
      }
    }
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            if_defeated: true
          }
          enemy_skill_id: 3910
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 3915
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 3914
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 3915
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 3911
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 3915
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 3914
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 3915
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 20
                      }
                      enemy_skill_id: 3907
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 40
                        use_chance: 100
                      }
                      enemy_skill_id: 3908
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
