  monster_id: 2790
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3985
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3983
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3945
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3937
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3938
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3939
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3946
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3942
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3941
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3943
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3947
        }
      }
      children {
        behavior {
          condition {
            use_chance: 65
          }
          enemy_skill_id: 3948
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
            trigger_enemies_remaining: 1
          }
          enemy_skill_id: 3949
        }
      }
      children {
        behavior {
          condition {
            use_chance: 15
          }
          enemy_skill_id: 3950
        }
      }
    }
  }
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3985
        }
      }
    }
    groups {
      group_type: UNKNOWN_USE
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3983
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3945
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3937
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3938
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3939
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3946
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3942
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3941
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3943
        }
      }
      children {
        behavior {
          condition {
          }
          enemy_skill_id: 3947
        }
      }
      children {
        behavior {
          condition {
            use_chance: 65
          }
          enemy_skill_id: 3948
        }
      }
      children {
        behavior {
          condition {
            use_chance: 20
            trigger_enemies_remaining: 1
          }
          enemy_skill_id: 3949
        }
      }
      children {
        behavior {
          condition {
            use_chance: 15
          }
          enemy_skill_id: 3950
        }
      }
    }
  }
