  monster_id: 2791
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3966
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 2964
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3967
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 2964
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: DISPEL_PLAYER
          condition {
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3956
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3957
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3958
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 3968
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 3979
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 3980
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 3969
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 3981
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 3970
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 8
              }
              children {
                behavior {
                  enemy_skill_id: 3963
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 3959
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 3973
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 3977
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 3975
                }
              }
            }
          }
        }
      }
    }
  }
