  monster_id: 2876
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 4220
        }
      }
      children {
        behavior {
          enemy_skill_id: 4348
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 4220
        }
      }
      children {
        behavior {
          enemy_skill_id: 4348
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 4226
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                    trigger_monsters: 2442
                    trigger_monsters: 2443
                  }
                  enemy_skill_id: 4228
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 4229
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 40
                  }
                  enemy_skill_id: 4230
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 4232
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                    if_attributes_available: true
                  }
                  enemy_skill_id: 4231
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4235
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                hp_threshold: 20
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 4223
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 20
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 4236
                }
              }
            }
          }
        }
      }
    }
  }
