  monster_id: 2898
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 7096
        }
      }
      children {
        behavior {
          enemy_skill_id: 7115
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 7115
        }
      }
    }
  }
