  monster_id: 2932
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 4609
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 4610
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 4611
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 4612
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 30
                        use_chance: 100
                      }
                      enemy_skill_id: 4614
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 30
                        use_chance: 100
                      }
                      enemy_skill_id: 4613
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 30
                        use_chance: 100
                      }
                      enemy_skill_id: 4614
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
