  monster_id: 2967
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 4704
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 4563
        }
      }
    }
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            if_defeated: true
          }
          enemy_skill_id: 4575
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: DISPEL_PLAYER
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 4567
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 4564
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 4565
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 4566
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 4570
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 4571
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 4572
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        global_one_time: true
                      }
                      enemy_skill_id: 4573
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 4571
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 4572
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 10
                        use_chance: 100
                      }
                      enemy_skill_id: 4574
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
