  monster_id: 299
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 40
          }
          children {
            behavior {
              enemy_skill_id: 45
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              condition {
                hp_threshold: 20
                use_chance: 50
              }
              enemy_skill_id: 83
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 40
              }
              enemy_skill_id: 45
            }
          }
        }
      }
    }
  }
