  monster_id: 3009
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 5050
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 5051
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
            if_attributes_available: true
          }
          children {
            behavior {
              enemy_skill_id: 5052
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 5051
            }
          }
        }
      }
    }
  }
