  monster_id: 3014
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 4954
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 4961
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4955
            }
          }
        }
      }
      children {
        group {
          condition {
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
                if_attributes_available: true
              }
              enemy_skill_id: 4956
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 4957
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_enemies_remaining: 1
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 4958
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 4960
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 4955
            }
          }
        }
      }
      children {
        group {
          condition {
            repeats_every: 4
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
                if_attributes_available: true
              }
              enemy_skill_id: 4956
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 4957
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 4959
            }
          }
        }
      }
    }
  }
