  monster_id: 3141
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 5417
        }
      }
      children {
        behavior {
          enemy_skill_id: 5418
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 5419
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5421
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 5422
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 5423
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 5424
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 5425
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                if_attributes_available: true
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 5426
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 5427
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 5428
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 5429
                }
              }
            }
          }
        }
      }
    }
  }
