  monster_id: 318
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 157
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 40
        use_chance: 100
        trigger_enemies_remaining: 1
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 158
        }
      }
    }
  }
  levels {
    level: 7
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 2598
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 100
        if_attributes_available: true
      }
      children {
        behavior {
          enemy_skill_id: 2601
        }
      }
    }
  }
