  monster_id: 3209
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 5808
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5811
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 5817
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 5818
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5812
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 80
                use_chance: 100
                repeats_every: 2
              }
              children {
                behavior {
                  enemy_skill_id: 5819
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 5817
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 5818
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 5813
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 5816
            }
          }
        }
      }
    }
  }
