  monster_id: 3260
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6876
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                use_chance: 50
              }
              enemy_skill_id: 6884
            }
          }
          children {
            behavior {
              enemy_skill_id: 6878
            }
          }
          children {
            behavior {
              enemy_skill_id: 6877
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6881
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  enemy_skill_id: 6882
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 6884
                }
              }
              children {
                behavior {
                  condition {
                    if_attributes_available: true
                  }
                  enemy_skill_id: 6883
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            behavior {
              enemy_skill_id: 6885
            }
          }
        }
      }
    }
  }
