  monster_id: 3327
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 6055
        }
      }
      children {
        behavior {
          enemy_skill_id: 5976
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 5979
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 5980
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 3
              }
              children {
                behavior {
                  enemy_skill_id: 5981
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 5982
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 5983
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 6
              }
              children {
                behavior {
                  enemy_skill_id: 5984
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 7
              }
              children {
                behavior {
                  enemy_skill_id: 5988
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    use_chance: 50
                  }
                  enemy_skill_id: 5994
                }
              }
              children {
                behavior {
                  condition {
                    use_chance: 100
                  }
                  enemy_skill_id: 5995
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 98
            use_chance: 100
            trigger_turn: 7
          }
          children {
            behavior {
              enemy_skill_id: 5989
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 5997
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 5993
                }
              }
            }
          }
        }
      }
    }
  }
