  monster_id: 353
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 197
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 16
              }
              children {
                behavior {
                  enemy_skill_id: 197
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 39
          }
          children {
            group {
              condition {
                hp_threshold: 40
                use_chance: 30
                trigger_turn: 1
                trigger_turn_end: 4
              }
              children {
                behavior {
                  enemy_skill_id: 139
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 40
                use_chance: 30
                trigger_turn: 6
                trigger_turn_end: 15
              }
              children {
                behavior {
                  enemy_skill_id: 139
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 40
                use_chance: 30
              }
              children {
                behavior {
                  enemy_skill_id: 139
                }
              }
            }
          }
        }
      }
    }
  }
