  monster_id: 3581
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 6989
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: MONSTER_STATUS
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 6998
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 6992
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 9
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 6994
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 6993
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 9
                trigger_turn: 9
              }
              children {
                behavior {
                  enemy_skill_id: 6997
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 5
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 6999
            }
          }
        }
      }
    }
  }
