  monster_id: 3751
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 13463
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 13467
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 13472
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 13473
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 13474
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 13475
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
                trigger_turn: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 13473
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 13474
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 13475
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 13468
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 13469
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 13476
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 13479
                }
              }
            }
          }
        }
      }
    }
  }
