  monster_id: 386
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 49
        use_chance: 100
        global_one_time: true
        trigger_turn: 1
      }
      children {
        behavior {
          enemy_skill_id: 33
        }
      }
    }
  }
