  monster_id: 386
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 50
                        use_chance: 100
                        global_one_time: true
                      }
                      enemy_skill_id: 33
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
