  monster_id: 3866
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 7939
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        use_chance: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 6388
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 7940
        }
      }
    }
  }
  levels {
    level: 2
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 7924
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        use_chance: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 6388
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 7925
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 7926
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 7933
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 7934
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 7935
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 7936
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 20
              }
              enemy_skill_id: 7937
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 7938
            }
          }
        }
      }
    }
  }
