  monster_id: 4033
  levels {
    level: 1
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 8520
        }
      }
    }
  }
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8511
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 8520
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 8512
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 8514
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 20
                  }
                  enemy_skill_id: 8515
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 15
                  }
                  enemy_skill_id: 8516
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 15
                  }
                  enemy_skill_id: 8517
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 15
                  }
                  enemy_skill_id: 8518
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 15
                    if_attributes_available: true
                  }
                  enemy_skill_id: 8519
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 8512
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 20
                use_chance: 100
                trigger_enemies_remaining: 1
              }
              enemy_skill_id: 8513
            }
          }
        }
      }
    }
  }
