  monster_id: 4076
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8628
        }
      }
      children {
        behavior {
          enemy_skill_id: 8627
        }
      }
      children {
        behavior {
          enemy_skill_id: 8626
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 8625
        }
      }
    }
  }
