  monster_id: 4076
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_monsters: 4094
            trigger_monsters: 4095
          }
          enemy_skill_id: 8628
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_monsters: 4091
            trigger_monsters: 4092
            trigger_monsters: 4093
          }
          enemy_skill_id: 8627
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 8626
        }
      }
    }
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            hp_threshold: 100
            if_defeated: true
          }
          enemy_skill_id: 8625
        }
      }
    }
  }
