  monster_id: 4091
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 8678
        }
      }
      children {
        behavior {
          enemy_skill_id: 8677
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 8676
        }
      }
    }
  }
