  monster_id: 4132
  levels {
    level: 4
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 3
          }
          children {
            behavior {
              enemy_skill_id: 8771
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 3
            if_attributes_available: true
          }
          children {
            behavior {
              enemy_skill_id: 8772
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 3
          }
          children {
            behavior {
              enemy_skill_id: 8773
            }
          }
        }
      }
    }
  }
