  monster_id: 433
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 39
        use_chance: 40
      }
      children {
        behavior {
          enemy_skill_id: 166
        }
      }
    }
  }
