  monster_id: 4344
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 13062
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 13065
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 13048
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13049
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 13050
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13051
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13052
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13056
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13053
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13054
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13055
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 60
                      }
                      enemy_skill_id: 13057
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 13058
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13052
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        trigger_enemies_remaining: 1
                      }
                      enemy_skill_id: 13060
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13049
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                        if_attributes_available: true
                      }
                      enemy_skill_id: 13050
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13051
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 25
                      }
                      enemy_skill_id: 13052
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 19
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 20
                        use_chance: 100
                      }
                      enemy_skill_id: 13061
                    }
                  }
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 1
                        use_chance: 100
                      }
                      enemy_skill_id: 13063
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
