  monster_id: 437
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 170
        }
      }
    }
  }
