  monster_id: 4389
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 9999
        }
      }
    }
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            if_defeated: true
          }
          enemy_skill_id: 9996
        }
      }
      children {
        behavior {
          condition {
            if_defeated: true
          }
          enemy_skill_id: 9996
        }
      }
    }
  }
  levels {
    level: 3
    groups {
      group_type: DEATH
      children {
        behavior {
          condition {
            if_defeated: true
          }
          enemy_skill_id: 9996
        }
      }
      children {
        behavior {
          condition {
            if_defeated: true
          }
          enemy_skill_id: 9996
        }
      }
    }
  }
