  monster_id: 444
  levels {
    level: 1
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 75
            use_chance: 100
            trigger_enemies_remaining: 1
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 203
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 40
            use_chance: 75
          }
          children {
            behavior {
              enemy_skill_id: 255
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 9
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                hp_threshold: 10
                use_chance: 100
              }
              enemy_skill_id: 253
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 75
                use_chance: 100
                trigger_enemies_remaining: 1
              }
              enemy_skill_id: 203
            }
          }
        }
      }
    }
  }
