  monster_id: 4606
  levels {
    level: 4
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 10271
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10272
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 2
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10277
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 3
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10273
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10278
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 5
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10274
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 6
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10277
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 7
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10275
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 8
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10278
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 9
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10276
                    }
                  }
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 1
              }
              children {
                group {
                  group_type: STANDARD
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                      }
                      enemy_skill_id: 10279
                    }
                  }
                  children {
                    behavior {
                      condition {
                        hp_threshold: 100
                        use_chance: 100
                        if_attributes_available: true
                      }
                      enemy_skill_id: 10276
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
