  monster_id: 465
  levels {
    level: 6
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 50
        use_chance: 40
      }
      children {
        behavior {
          enemy_skill_id: 181
        }
      }
    }
  }
