  monster_id: 470
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 10
      }
      children {
        behavior {
          enemy_skill_id: 176
        }
      }
    }
  }
