  monster_id: 4804
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_monsters: 4796
            trigger_monsters: 4797
          }
          enemy_skill_id: 11163
        }
      }
      children {
        behavior {
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          enemy_skill_id: 11162
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 11175
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11164
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 11168
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                    if_attributes_available: true
                  }
                  enemy_skill_id: 11167
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 11123
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 2
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                    if_attributes_available: true
                  }
                  enemy_skill_id: 11167
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 50
                  }
                  enemy_skill_id: 11123
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 11169
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 24
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11172
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 11173
                }
              }
            }
          }
        }
      }
    }
  }
