  monster_id: 4836
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11674
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 1
                trigger_turn_end: 4
              }
              children {
                behavior {
                  enemy_skill_id: 11681
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 11679
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 6
                trigger_turn_end: 9
              }
              children {
                behavior {
                  enemy_skill_id: 11681
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_turn: 10
              }
              children {
                behavior {
                  enemy_skill_id: 11684
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 5
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11679
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 5
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 11681
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 11682
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 6
          }
          children {
            group {
              condition {
                use_chance: 100
                trigger_enemies_remaining: 1
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11683
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
              }
              children {
                behavior {
                  enemy_skill_id: 11685
                }
              }
            }
          }
        }
      }
    }
  }
