  monster_id: 4838
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 12312
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 12315
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 12318
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 12319
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 12320
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 74
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 12321
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 12315
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 12318
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 12319
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 12320
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 3
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 12325
            }
          }
        }
      }
    }
  }
