  monster_id: 4950
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 11983
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 11984
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 11987
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 33
                  }
                  enemy_skill_id: 11988
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 34
                  }
                  enemy_skill_id: 11989
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 11990
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 11993
            }
          }
        }
      }
    }
  }
