  monster_id: 500075
  levels {
    level: 1
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
        use_chance: 60
        if_attributes_available: true
      }
      children {
        behavior {
          enemy_skill_id: 13994
        }
      }
    }
  }
