  monster_id: 500154
  levels {
    level: 1
    groups {
      group_type: DEATH
      condition {
        hp_threshold: 100
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 14587
        }
      }
    }
  }
