  monster_id: 5363
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 13563
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13568
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 6388
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 13568
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 13567
            }
          }
        }
      }
    }
  }
  levels {
    level: 2
    groups {
      group_type: PASSIVE
      children {
        behavior {
          enemy_skill_id: 13563
        }
      }
    }
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 13552
        }
      }
    }
    groups {
      group_type: DEATH
      condition {
        if_defeated: true
      }
      children {
        behavior {
          enemy_skill_id: 6388
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 13553
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 79
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 13561
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
                trigger_enemies_remaining: 1
              }
              enemy_skill_id: 13564
            }
          }
          children {
            behavior {
              condition {
                use_chance: 20
              }
              enemy_skill_id: 13565
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 14
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 13566
            }
          }
        }
      }
    }
  }
