  monster_id: 5465
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 14055
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
                trigger_turn_end: 3
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14060
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14061
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14062
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14063
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 4
              }
              children {
                behavior {
                  enemy_skill_id: 14059
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14060
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14061
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14062
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14063
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 50
            trigger_turn: 1
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 100
              }
              enemy_skill_id: 14058
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 14060
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 14061
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 14062
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 25
              }
              enemy_skill_id: 14063
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                  }
                  enemy_skill_id: 14058
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 100
                    trigger_enemies_remaining: 1
                  }
                  enemy_skill_id: 14064
                }
              }
            }
          }
          children {
            group {
              condition {
                trigger_turn: 4
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14060
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14061
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14062
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 25
                  }
                  enemy_skill_id: 14063
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                trigger_turn: 5
              }
              children {
                behavior {
                  enemy_skill_id: 14059
                }
              }
            }
          }
        }
      }
    }
  }
