  monster_id: 548
  levels {
    level: 5
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 25
        use_chance: 100
        repeats_every: 6
      }
      children {
        behavior {
          enemy_skill_id: 223
        }
      }
    }
  }
