  monster_id: 562
  levels {
    level: 5
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 40
              }
              enemy_skill_id: 443
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 60
              }
              enemy_skill_id: 442
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 441
            }
          }
        }
      }
    }
  }
