  monster_id: 5637
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 15040
        }
      }
      children {
        behavior {
          enemy_skill_id: 15041
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        behavior {
          enemy_skill_id: 15029
        }
      }
    }
  }
