  monster_id: 650
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 325
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 90
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 70
            use_chance: 75
          }
          children {
            behavior {
              enemy_skill_id: 326
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 49
            trigger_turn: 2
          }
          children {
            behavior {
              condition {
                hp_threshold: 50
                use_chance: 100
              }
              enemy_skill_id: 328
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 70
                use_chance: 75
              }
              enemy_skill_id: 326
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                hp_threshold: 50
                use_chance: 100
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 328
                }
              }
            }
          }
          children {
            group {
              children {
                behavior {
                  condition {
                    hp_threshold: 30
                    use_chance: 75
                  }
                  enemy_skill_id: 327
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 70
                    use_chance: 75
                  }
                  enemy_skill_id: 326
                }
              }
            }
          }
        }
      }
    }
  }
