  monster_id: 713
  levels {
    level: 5
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 74
        use_chance: 70
      }
      children {
        behavior {
          enemy_skill_id: 352
        }
      }
    }
  }
