  monster_id: 746
  levels {
    level: 3
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 1064
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 20
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 557
        }
      }
    }
  }
