  monster_id: 753
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 558
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 70
          }
          children {
            behavior {
              enemy_skill_id: 560
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 59
          }
          children {
            behavior {
              condition {
                hp_threshold: 60
                use_chance: 60
              }
              enemy_skill_id: 559
            }
          }
          children {
            behavior {
              condition {
                hp_threshold: 100
                use_chance: 70
              }
              enemy_skill_id: 560
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 20
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 561
            }
          }
        }
      }
    }
  }
