  monster_id: 758
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 3097
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
          }
          children {
            group {
              condition {
                trigger_turn: 1
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 70
                  }
                  enemy_skill_id: 3098
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 70
                  }
                  enemy_skill_id: 3100
                }
              }
            }
          }
          children {
            group {
              condition {
                repeats_every: 4
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 70
                  }
                  enemy_skill_id: 3098
                }
              }
              children {
                behavior {
                  condition {
                    hp_threshold: 100
                    use_chance: 70
                  }
                  enemy_skill_id: 3100
                }
              }
            }
          }
          children {
            group {
              condition {
                hp_threshold: 100
                use_chance: 100
                repeats_every: 4
              }
              children {
                behavior {
                  enemy_skill_id: 3101
                }
              }
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3099
            }
          }
        }
      }
    }
  }
