  monster_id: 761
  levels {
    level: 1
    groups {
      group_type: PASSIVE
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 4463
        }
      }
    }
    groups {
      group_type: PREEMPT
      condition {
        hp_threshold: 100
        use_chance: 100
      }
      children {
        behavior {
          enemy_skill_id: 4449
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4452
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 4455
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 4458
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 4461
            }
          }
        }
      }
      children {
        group {
          condition {
            hp_threshold: 100
            use_chance: 100
            repeats_every: 4
          }
          children {
            behavior {
              enemy_skill_id: 4462
            }
          }
        }
      }
    }
  }
