  monster_id: 925
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 683
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 686
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 685
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 686
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 684
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 686
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 685
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 3178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 2178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 1178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 687
            }
          }
        }
      }
    }
  }
  levels {
    level: 5
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 683
        }
      }
    }
    groups {
      group_type: STANDARD
      condition {
        hp_threshold: 100
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 686
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 685
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 686
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 684
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 686
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            trigger_turn: 6
          }
          children {
            behavior {
              enemy_skill_id: 685
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 4178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 2
          }
          children {
            behavior {
              enemy_skill_id: 3178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 3
          }
          children {
            behavior {
              enemy_skill_id: 2178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 4
          }
          children {
            behavior {
              enemy_skill_id: 1178
            }
          }
        }
      }
      children {
        group {
          condition {
            use_chance: 100
            repeats_every: 5
            trigger_turn: 5
          }
          children {
            behavior {
              enemy_skill_id: 687
            }
          }
        }
      }
    }
  }
