  monster_id: 990
  levels {
    level: 1
    groups {
      group_type: PREEMPT
      children {
        behavior {
          enemy_skill_id: 3878
        }
      }
    }
    groups {
      group_type: STANDARD
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 101
            use_chance: 100
          }
          children {
            behavior {
              enemy_skill_id: 3879
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 99
            use_chance: 100
            if_attributes_available: true
          }
          children {
            behavior {
              enemy_skill_id: 3880
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 69
            use_chance: 100
            trigger_turn: 1
          }
          children {
            behavior {
              enemy_skill_id: 3881
            }
          }
        }
      }
      children {
        group {
          group_type: STANDARD
          condition {
            hp_threshold: 29
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 2
                trigger_turn: 1
              }
              children {
                behavior {
                  enemy_skill_id: 3882
                }
              }
            }
          }
          children {
            group {
              condition {
                use_chance: 100
                repeats_every: 2
                trigger_turn: 2
              }
              children {
                behavior {
                  enemy_skill_id: 3883
                }
              }
            }
          }
        }
      }
    }
  }
